clean: true
objc: false
readme: Readme.md
framework_root: MBurgerSwift
module_version: 1.0.17
sdk: iphonesimulator

author: Mumble
author_url: https://mumbleideas.it/
github_url: https://github.com/Mumble-SRL/MBurgerSwift

xcodebuild_arguments:
    - "-workspace"
    - "MBurgerSwift.xcworkspace"
    - "-scheme"
    - "MBurgerSwift"

theme: fullwidth

custom_categories:

  - name: MBBlock
    children:
    - MBBlock
  - name: MBSection
    children:
    - MBSection
  - name: MBClient
    children:
    - MBClient
  - name: MBManager
    children:
    - MBManager
    - MBApiManager
  - name: MBElement
    children:
    - MBElementProtocol
    - MBElement
    - MBElementFactory
    - MBTextElement
    - MBDropdownElement
    - MBDropdownElementOption
    - MBPollElement
    - MBMarkdownElement
    - MBGeneralElement
    - MBAddressElement
    - MBDateElement
    - MBImagesElement
    - MBMedia
    - MBImage
    - MBMediaElement
    - MBCheckboxElement
    - MBRelationElement
    - MBRelation
    - MBElementType
    - MBMediaType
    - MBColorElement
    - MBMultipleElement  
    - MBMultipleElementOption
  - name: MBParameter
    children:
    - MBParameter
    - MBFilterParameter
    - MBGeneralParameter
    - MBGeofenceParameter
    - MBPaginationParameter
    - MBSortParameter
  - name: MBDecodable
    children:
    - MBDecoder
    - MBDecodable
  - name: MBAuth
    children:
    - MBAuth
    - MBAuthContractAcceptanceParameter
    - MBUser
    - MBUserContractStatus
    - MBUserPublishedSection
    - MBAuthSocialTokenType
  - name: MBPagination
    children:
    - MBPaginationInfo
  - name: MBProject
    children:
    - MBProject
    - MBLegalContract
  - name: MBPlugin
    children:
    - MBPlugin
    - MBPluginsManager
    - MBApplicationStartupBlock
  - name: Public Extension
    children:
    - Collection
  - name: MBUtilities
    children: 
    - MBUtilities
